# Generated by Django 3.0 on 2020-01-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('selector', models.CharField(choices=[('id', 'ID'), ('class', 'Class')], max_length=255)),
                ('selector_label', models.CharField(max_length=500)),
                ('search_text', models.CharField(max_length=500)),
                ('notify_when', models.IntegerField(choices=[(1, 'If text found'), (2, 'If text not found')])),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_logs', to='crawler.Crawler')),
            ],
        ),
    ]
